### ISSUE TITLE
Add cards in template preview mode

### ISSUE THREAD

**Issue by TheNando** [TheNando/cardinal#33]
In preview mode on the template editor, use should be able to create cards and edit their data.

- [x] Add a new card
- [x] ~Populate card data~
- [x] Realtime card preview
- [x] ~Table edit mode~
